"""Markdown reporter — renders experiment results as a human-readable Markdown diff summary."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel

from ease_core.plugins.base import ExecutionContext, Reporter


class MarkdownReporter:
    """Renders an experiment as a Markdown report suitable for PR comments or email."""

    name = "markdown"
    version = "1.0.0"
    input_schema: type[BaseModel] = BaseModel
    output_schema: type[BaseModel] = BaseModel

    def run(self, ctx: ExecutionContext, input_data: BaseModel) -> BaseModel:
        report = self._generate_markdown(ctx, input_data)

        output_path = ctx.workspace.scratch / "report.md"
        output_path.write_text(report, encoding="utf-8")

        class RawReport(BaseModel):
            path: str
            content: str

        return RawReport(path=str(output_path), content=report)

    def healthcheck(self) -> bool:
        return True

    @staticmethod
    def _generate_markdown(ctx: ExecutionContext, data: BaseModel) -> str:
        lines = [
            f"# EASE Experiment Report: `{ctx.experiment_id}`",
            "",
            f"- **Generated:** {datetime.utcnow().isoformat()}",
            f"- **Experiment ID:** `{ctx.experiment_id}`",
            "",
            "## Summary",
            "",
            "This report summarizes the optimization experiment results.",
            "",
            "## Configuration",
            "",
            f"```yaml",
            f"{str(ctx.config)[:1000]}",
            f"```",
            "",
            "## Results",
            "",
            f"```",
            f"{str(data.model_dump() if hasattr(data, 'model_dump') else data)[:2000]}",
            f"```",
            "",
            "---",
            "",
            "*Report generated by EASE (Energy-Aware Software Engineering Platform)*",
            "",
        ]
        return "\n".join(lines)
